### ISSUE TITLE
Vest target equilibrium

### ISSUE THREAD

**Issue by JisungKang** [JisungKang/SNU_VEST#1]

**Comment by JonginWang** [comment]
- Device: VEST
- Parameters
![image](https://cloud.githubusercontent.com/assets/20056678/16367313/062c7ca2-3c5d-11e6-8c67-d3bbb1c13f0c.png)

- ne, Te, and j profiles (Both in bell shapes)
![image](https://cloud.githubusercontent.com/assets/20056678/16367315/0db02262-3c5d-11e6-8677-6fd70b48af7d.png)
ne profile
![image](https://cloud.githubusercontent.com/assets/20056678/16367320/2096f4b4-3c5d-11e6-90e0-21efddfc6b3b.png)
Te profile
![image](https://cloud.githubusercontent.com/assets/20056678/16367322/2c372226-3c5d-11e6-94e6-839566d1e0d8.png)
Pressure profile
![image](https://cloud.githubusercontent.com/assets/20056678/16367329/39098cf0-3c5d-11e6-8220-63adb1db8bdb.png)
Current Profile

- CHEASE Setup
NCSCAL: 2 (Physicla value of Ip is 0.1e6)
NPROPT: 2

![image](https://cloud.githubusercontent.com/assets/20056678/16367984/5bde4ba6-3c64-11e6-95c0-ff8e6d571e16.png)


- CHEASE Result
q0: 1.5452
qedge: 13.2350
qmin: 1.5452
rhopsiqmin: 0
q95: 7.8600
epsilon_edge: 0.7500
kappa_edge: 2
delta_bottom: 0.3999
delta_upper: 0.3998
delta: 0.3999
scale: 0.1541
psiaxis: -0.2621
psiaxis2pi: -1.6469
r0exp: 0.4000
b0exp: 0.1000
ipchease: 3.1417
ip_phys: 1.0000e+05
li: 0.5786
beta_exp: 9.5184e-04
betap: 0.0039
betan_exp: 0.0286
betan: 0.0286
volumchease: 20.5413
rgeomchease: 1.0000
achease: 0.7500
ibs_fraction_0coll: 0.0030
ibs_fraction_fullcoll: 0.0026
areachease: 3.5344
surfacechease: 41.8091
poloidallengthchease: 7.3540

![vest_bb_beta_p](https://cloud.githubusercontent.com/assets/20056678/16368756/210078de-3c6d-11e6-8079-dec4fb621ff0.jpg)
poloidal beta

![vest_bb_jbs](https://cloud.githubusercontent.com/assets/20056678/16368758/23b387ec-3c6d-11e6-9811-a31345cb9e90.jpg)
jbs /w. coll

![vest_bb_jbs_zerocoll](https://cloud.githubusercontent.com/assets/20056678/16368761/2cb7ecac-3c6d-11e6-87a3-afe640bd1ae5.jpg)
jbs /w.o. coll

![vest_bb_q](https://cloud.githubusercontent.com/assets/20056678/16368764/3183f514-3c6d-11e6-9b74-cb0ad13471b2.jpg)
q profile

**Comment by JonginWang** [comment]
- Device: VEST
- Parameters
![image](https://cloud.githubusercontent.com/assets/20056678/16368883/97d900f6-3c6e-11e6-8318-7b3a676fedeb.png)

- ne, Te, and j profiles (Both in bell shapes)
![image](https://cloud.githubusercontent.com/assets/20056678/16367315/0db02262-3c5d-11e6-8677-6fd70b48af7d.png)
ne profile
![image](https://cloud.githubusercontent.com/assets/20056678/16367320/2096f4b4-3c5d-11e6-90e0-21efddfc6b3b.png)
Te profile
![image](https://cloud.githubusercontent.com/assets/20056678/16367322/2c372226-3c5d-11e6-94e6-839566d1e0d8.png)
Pressure profile
![image](https://cloud.githubusercontent.com/assets/20056678/16368892/a7083eb6-3c6e-11e6-9520-e7c0728e1775.png)
Current Profile

- CHEASE Setup
NCSCAL: 2 (Physicla value of Ip is 0.1e6)
NPROPT: 2

![image](https://cloud.githubusercontent.com/assets/20056678/16368930/0895c874-3c6f-11e6-8a18-1812d5f0993f.png)

- CHEASE Result
q0: 0.9569
qedge: 15.0670
qmin: 0.9536
rhopsiqmin: 0.0857
q95: 7.1336
epsilon_edge: 0.7500
kappa_edge: 2
delta_bottom: 0.3999
delta_upper: 0.3999
delta: 0.3999
scale: 0.2550
psiaxis: -0.3429
psiaxis2pi: -2.1546
r0exp: 0.4000
b0exp: 0.1000
ipchease: 3.1416
ip_phys: 1.0000e+05
li: 0.8000
beta_exp: 0.0023
betap: 0.0093
betan_exp: 0.0694
betan: 0.0694
volumchease: 20.5420
rgeomchease: 1.0000
achease: 0.7500
ibs_fraction_0coll: 0.0062
ibs_fraction_fullcoll: 0.0057
areachease: 3.5347
surfacechease: 41.8091
poloidallengthchease: 7.3540

![vest_bl_beta_p](https://cloud.githubusercontent.com/assets/20056678/16368988/c7bdae38-3c6f-11e6-8def-954feb966868.jpg)
poloidal beta

![vest_bl_jbs](https://cloud.githubusercontent.com/assets/20056678/16368990/d22cae14-3c6f-11e6-8c7b-eee42dca5be5.jpg)
jbs /w. coll

![vest_bl_jbs_zerocoll](https://cloud.githubusercontent.com/assets/20056678/16368992/da4d3d34-3c6f-11e6-8e14-09a88b6bc0f2.jpg)
jbs /w.o. coll

![vest_bl_q](https://cloud.githubusercontent.com/assets/20056678/16368994/dfa7fc10-3c6f-11e6-9c0a-41f1559b9c3f.jpg)
q profile

**Comment by JonginWang** [comment]
- Device: VEST
- Parameters
![image](https://cloud.githubusercontent.com/assets/20056678/16367313/062c7ca2-3c5d-11e6-8c67-d3bbb1c13f0c.png)

- ne, Te, and j profiles (Both in bell shapes)
![image](https://cloud.githubusercontent.com/assets/20056678/16369212/48d99aac-3c72-11e6-90b8-ea5f09b1053c.png)
ne profile
![image](https://cloud.githubusercontent.com/assets/20056678/16369219/544315d0-3c72-11e6-84c0-c4c4a296532a.png)
Te profile
![image](https://cloud.githubusercontent.com/assets/20056678/16369539/7175f3c4-3c73-11e6-9d5f-574a81033382.png)
Pressure profile
![image](https://cloud.githubusercontent.com/assets/20056678/16367329/39098cf0-3c5d-11e6-8220-63adb1db8bdb.png)
Current Profile

- CHEASE Setup
NCSCAL: 2 (Physicla value of Ip is 0.1e6)
NPROPT: 2
![image](https://cloud.githubusercontent.com/assets/20056678/16369545/7e2209fa-3c73-11e6-954f-0a2cddc49b05.png)

- CHEASE Result
q0: 1.5443
qedge: 13.2280
qmin: 1.5443
rhopsiqmin: 0
q95: 7.8590
epsilon_edge: 0.7500
kappa_edge: 2
delta_bottom: 0.3999
delta_upper: 0.3998
delta: 0.3999
scale: 0.1541
psiaxis: -0.2621
psiaxis2pi: -1.6469
r0exp: 0.4000
b0exp: 0.1000
ipchease: 3.1417
ip_phys: 1.0000e+05
li: 0.5786
beta_exp: 5.5661e-04
betap: 0.0022
betan_exp: 0.0167
betan: 0.0167
volumchease: 20.5413
rgeomchease: 1.0000
achease: 0.7500
ibs_fraction_0coll: 0.0024
ibs_fraction_fullcoll: 0.0020
areachease: 3.5344
surfacechease: 41.8091
poloidallengthchease: 7.3540

![vest_lb_beta_p](https://cloud.githubusercontent.com/assets/20056678/16369630/024b63e8-3c74-11e6-8060-3bd939e3ada2.jpg)
poloidal beta

![vest_lb_jbs](https://cloud.githubusercontent.com/assets/20056678/16369664/0dd4f35a-3c74-11e6-951a-158a8f8bd4fb.jpg)
jbs /w. coll

![vest_lb_jbs_zerocoll](https://cloud.githubusercontent.com/assets/20056678/16369666/13babcbe-3c74-11e6-9eb9-a619205c906c.jpg)
jbs /w.o. coll

![vest_lb_q](https://cloud.githubusercontent.com/assets/20056678/16369668/185cc118-3c74-11e6-8d25-5cb67e81d4cd.jpg)
q profile

**Comment by JonginWang** [comment]
- Device: VEST
- Parameters
![image](https://cloud.githubusercontent.com/assets/20056678/16367313/062c7ca2-3c5d-11e6-8c67-d3bbb1c13f0c.png)

- ne, Te, and j profiles (Both in bell shapes)
![image](https://cloud.githubusercontent.com/assets/20056678/16369212/48d99aac-3c72-11e6-90b8-ea5f09b1053c.png)
ne profile
![image](https://cloud.githubusercontent.com/assets/20056678/16369219/544315d0-3c72-11e6-84c0-c4c4a296532a.png)
Te profile
![image](https://cloud.githubusercontent.com/assets/20056678/16369539/7175f3c4-3c73-11e6-9d5f-574a81033382.png)
Pressure profile
![image](https://cloud.githubusercontent.com/assets/20056678/16369707/7edba29c-3c74-11e6-8f9c-66f0779450b1.png)
Current Profile

- CHEASE Setup
NCSCAL: 2 (Physicla value of Ip is 0.1e6)
NPROPT: 2
![image](https://cloud.githubusercontent.com/assets/20056678/16369711/89d224c8-3c74-11e6-9414-51cc1fa3a299.png)

- CHEASE Result
q0: 0.9563
qedge: 15.0520
qmin: 0.9529
rhopsiqmin: 0.0857
q95: 7.1327
epsilon_edge: 0.7500
kappa_edge: 2
delta_bottom: 0.3999
delta_upper: 0.3999
delta: 0.3999
scale: 0.2551
psiaxis: -0.3429
psiaxis2pi: -2.1545
r0exp: 0.4000
b0exp: 0.1000
ipchease: 3.1416
ip_phys: 1.0000e+05
li: 0.7999
beta_exp: 0.0013
betap: 0.0051
betan_exp: 0.0389
betan: 0.0389
volumchease: 20.5420
rgeomchease: 1.0000
achease: 0.7500
ibs_fraction_0coll: 0.0043
ibs_fraction_fullcoll: 0.0039
areachease: 3.5347
surfacechease: 41.8091
poloidallengthchease: 7.3540

![vest_ll_beta_p](https://cloud.githubusercontent.com/assets/20056678/16369746/e41cfd5e-3c74-11e6-8d9b-57b66f4e69a3.jpg)
poloidal beta

![vest_ll_jbs](https://cloud.githubusercontent.com/assets/20056678/16369748/e81f5910-3c74-11e6-9a33-61e7ab5ed9e5.jpg)
jbs /w. coll

![vest_ll_jbs_zerocoll](https://cloud.githubusercontent.com/assets/20056678/16369749/ead3260a-3c74-11e6-8d19-fa2d547967d4.jpg)
jbs /w.o. coll

![vest_ll_q](https://cloud.githubusercontent.com/assets/20056678/16369753/ee5e0ae2-3c74-11e6-8751-e8699f16a6c7.jpg)
q profile

**Comment by JonginWang** [comment]
Current profile과 Pressure profile을 다소 변화시켰을 때
- Current의 경우 flux shape 가운데 전류가 집중되는 형태보다 Edge에 고루 퍼진 경우 jbs fraction이 증가
- Pressure의 경우 Density와 Temperature에 의해 Center peaked 형태가 되어야 하며, grad의 크기가 edge로 올 수록 증가하는 형태여야 좀 더 physical한 값을 얻을 수 있음

PLAN

* 2016.06.27 (or ASAP)
- Current의 경우 
 1. 중심에 전류가 집중된 필라멘트 형태 
 2. 중심에 Hollow한 형태
- Pressure의 경우 
 1. 밀도가 종형인 경우, Center 피크 후에 plateau가 있는 경우, Pedestal이 있는 경우
 2. 온도가 종형인 경우, Center 피크 후에 plateau가 있는 경우, Pedestal이 있는 경우
를 조합하여 약 18가지 형태를 가지고 실험을 진행.

* 이후
- 가장 jbs가 높은 case를 선정
- 가장 VEST에서 구현 가능한 scenario 선정
