### ISSUE TITLE
VEST benchmark with various equilibrium solver

### ISSUE THREAD

**Issue by JisungKang** [JisungKang/SNU_VEST#3]
ESC

HELENA

others?

**Comment by JisungKang** [comment]
- ESC

  path /home/fatema/astra/astra_6.0/myASTRA

  run command -  .exe/astra VEST VEST

  exp file  equ file  path   /home/fatema/astra/astra_6.0/myASTRA/exp  

                                    /home/fatema/astra/astra_6.0/myASTRA/equ

**Comment by JonginWang** [comment]
Results

1. setting

(1) profile of ne, te, and ti: peak*(1-norm_psi^2)^alpha
(2) ne0, te0, ti0
![image](https://cloud.githubusercontent.com/assets/20056678/17049405/2c82c76a-5028-11e6-8092-07595b664274.png)

(3) alpha_ne: 0.4, 0.7, 1.5     alpha_te: 0.4, 0.7, 1.5
(4) q profile and mu profile
![image](https://cloud.githubusercontent.com/assets/20056678/17049406/32b78c42-5028-11e6-80fb-5ce5b5d7af7a.png)
![image](https://cloud.githubusercontent.com/assets/20056678/17049408/38d314c0-5028-11e6-8956-bad866b9012f.png)

2. results

(1) set1: alpha_ne: 0.4 alpha_te: 0.7

![astra_vest_set1_rhoparams](https://cloud.githubusercontent.com/assets/20056678/17049524/c21c705a-5028-11e6-8f2f-e67328e19b6d.png)

(2) set1: alpha_ne: 0.7 alpha_te: 0.7
![astra_vest_set2_rhoparams](https://cloud.githubusercontent.com/assets/20056678/17049528/c465abd8-5028-11e6-9b92-47c4da23491f.png)

(3) set1: alpha_ne: 1.5 alpha_te: 0.7
![astra_vest_set3_rhoparams](https://cloud.githubusercontent.com/assets/20056678/17049534/cae970ac-5028-11e6-860b-c71934a545e5.png)

(4) set1: alpha_ne: 0.4 alpha_te: 0.4
![astra_vest_set4_rhoparams](https://cloud.githubusercontent.com/assets/20056678/17049535/cca67516-5028-11e6-9a7e-bd159d67805b.png)

(5) set1: alpha_ne: 0.4 alpha_te: 1.5
![astra_vest_set5_rhoparams](https://cloud.githubusercontent.com/assets/20056678/17049539/cf85f4f0-5028-11e6-933d-432f8e0f72b1.png)

**Comment by JonginWang** [comment]
1. Figured out why CHEASE matlab does not work for some EXPEQ files.

- reason: low values of current profile input. No less than .1 order

2. Among previous cases, calculation of case#4 in CHEASE has been conducted, and the results are bellow.

q0: 0.9019
qedge: 2.3902
qmin: 0.7813
rhopsiqmin: 0.6786
q95: 1.9209
epsilon_edge: 0.7500
kappa_edge: 2
delta_bottom: 0.3999
delta_upper: 0.3998
delta: 0.3999
scale: 1.1065
psiaxis: -1.2405
psiaxis2pi: -7.7944
r0exp: 0.4000
b0exp: 0.1000
ipchease: 15.7080
ip_phys: 5.0000e+05
li: 0.4896
beta_exp: 0.0617
betap: 0.0104
betan_exp: 0.3701
betan: 0.3701
volumchease: 20.5412
rgeomchease: 1.0000
achease: 0.7500
ibs_fraction_0coll: 0.0046
ibs_fraction_fullcoll: 0.0044
areachease: 3.5343
surfacechease: 41.8091
poloidallengthchease: 7.3540

contour
![contour](https://cloud.githubusercontent.com/assets/20056678/17090234/de299e74-5269-11e6-9bd0-90cd63ac6b9e.jpg)


pressure
![press](https://cloud.githubusercontent.com/assets/20056678/17090166/1938f646-5269-11e6-818f-e190e15d7a59.jpg)


current (I*)
![istar](https://cloud.githubusercontent.com/assets/20056678/17090167/1b5021fc-5269-11e6-8b0f-2f35229e291a.jpg)


q profile
![q](https://cloud.githubusercontent.com/assets/20056678/17090169/20f4c310-5269-11e6-83cf-c58a870c992c.jpg)


beta_p
![betap](https://cloud.githubusercontent.com/assets/20056678/17090170/226fca82-5269-11e6-9c7c-8c387334b9c0.jpg)


j_BS (no collision)
![jbsnocoll](https://cloud.githubusercontent.com/assets/20056678/17090173/248eaff4-5269-11e6-8be3-2b9bf49d03a3.jpg)


j_BS
![jbs](https://cloud.githubusercontent.com/assets/20056678/17090174/26b7bf32-5269-11e6-8ba7-72d47d5bcbca.jpg)
